-- Add company scoping to requisitions and purchase_orders, and create GRN tables
-- Compatible with H2 and Postgres

ALTER TABLE requisitions ADD COLUMN company_id BIGINT;
ALTER TABLE purchase_orders ADD COLUMN company_id BIGINT;

-- Add foreign keys if the DB supports it. For H2 this should work.
ALTER TABLE requisitions ADD CONSTRAINT fk_requisition_company FOREIGN KEY (company_id) REFERENCES companies(company_id);
ALTER TABLE purchase_orders ADD CONSTRAINT fk_po_company FOREIGN KEY (company_id) REFERENCES companies(company_id);

-- Create GRN header
CREATE TABLE IF NOT EXISTS grns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grn_number VARCHAR(100) NOT NULL,
  company_id BIGINT,
  vendor_id BIGINT,
  received_at TIMESTAMP,
  notes VARCHAR(1000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- unique index for grn_number
CREATE UNIQUE INDEX IF NOT EXISTS ux_grns_grn_number ON grns(grn_number);

ALTER TABLE grns ADD CONSTRAINT fk_grn_company FOREIGN KEY (company_id) REFERENCES companies(company_id);
ALTER TABLE grns ADD CONSTRAINT fk_grn_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id);

-- Create GRN lines
CREATE TABLE IF NOT EXISTS grn_lines (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grn_id BIGINT NOT NULL,
  po_line_id BIGINT,
  received_qty INT,
  received_price NUMERIC(12,2),
  line_total NUMERIC(14,2),
  uom VARCHAR(50)
);

ALTER TABLE grn_lines ADD CONSTRAINT fk_grnline_grn FOREIGN KEY (grn_id) REFERENCES grns(id);
ALTER TABLE grn_lines ADD CONSTRAINT fk_grnline_polyne FOREIGN KEY (po_line_id) REFERENCES purchase_order_lines(id);
