-- Persistent vendor inbox read/unread state per PO per vendor
CREATE TABLE IF NOT EXISTS vendor_inbox_events (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id       BIGINT NOT NULL,
  vendor_id   BIGINT NOT NULL,
  status      VARCHAR(30) NOT NULL DEFAULT 'UNREAD',
  read_at     TIMESTAMP,
  ack_at      TIMESTAMP,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_vendor_inbox_po_vendor
  ON vendor_inbox_events(po_id, vendor_id);

ALTER TABLE vendor_inbox_events
  ADD CONSTRAINT fk_vie_po     FOREIGN KEY (po_id)     REFERENCES purchase_orders(id),
  ADD CONSTRAINT fk_vie_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id);
