-- PO dispatch log — records each time a PO is dispatched (email/EDI stub)
CREATE TABLE IF NOT EXISTS po_dispatch_log (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id        BIGINT NOT NULL,
  dispatch_type VARCHAR(20) NOT NULL DEFAULT 'EMAIL',  -- EMAIL | EDI | MANUAL
  recipient    VARCHAR(255),
  sent_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status       VARCHAR(20) NOT NULL DEFAULT 'SENT',    -- SENT | FAILED | PENDING
  error_msg    VARCHAR(500),
  payload_ref  VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_dispatch_po ON po_dispatch_log(po_id);

ALTER TABLE po_dispatch_log
  ADD CONSTRAINT fk_dispatch_po FOREIGN KEY (po_id) REFERENCES purchase_orders(id);
